LangString addOrReinstall ${LANG_NEPALI} "कम्पोनेन्टहरू थप्नुहोस्/पुनः इन्स्टल गर्नुहोस्"
LangString alreadyInstalled ${LANG_NEPALI} "पहिले नै इन्स्टल गरिएको छ"
LangString alreadyInstalledLong ${LANG_NEPALI} "${PRODUCTNAME} ${VERSION} पहिले नै इन्स्टल गरिएको छ। तपाईंले गर्न चाहनुभएको कार्य छान्नुहोस् र जारी राख्न अर्को बटनमा क्लिक गर्नुहोस्।"
LangString appRunning ${LANG_NEPALI} "{{product_name}} चलिरहेको छ! कृपया पहिले यसलाई बन्द गरेर फेरि प्रयास गर्नुहोस्।"
LangString appRunningOkKill ${LANG_NEPALI} "{{product_name}} चलिरहेको छ!$\nयसलाई जबरजस्ती बन्द गर्न OK मा क्लिक गर्नुहोस्"
LangString chooseMaintenanceOption ${LANG_NEPALI} "गर्नुपर्ने मर्मतसम्भार विकल्प छान्नुहोस्।"
LangString choowHowToInstall ${LANG_NEPALI} "${PRODUCTNAME} कसरी इन्स्टल गर्न चाहनुहुन्छ, छान्नुहोस्।"
LangString createDesktop ${LANG_NEPALI} "डेस्कटप सर्टकट बनाउनुहोस्"
LangString dontUninstall ${LANG_NEPALI} "अनइन्स्टल नगर्नुहोस्"
LangString dontUninstallDowngrade ${LANG_NEPALI} "अनइन्स्टल नगर्नुहोस् (यस इन्स्टलरमा अनइन्स्टल नगरी पुरानो संस्करणमा फर्कन अनुमति छैन)"
LangString failedToKillApp ${LANG_NEPALI} "{{product_name}} बन्द गर्न सकिएन। कृपया पहिले यसलाई बन्द गरेर फेरि प्रयास गर्नुहोस्"
LangString installingWebview2 ${LANG_NEPALI} "WebView2 इन्स्टल हुँदैछ..."
LangString newerVersionInstalled ${LANG_NEPALI} "${PRODUCTNAME} को नयाँ संस्करण पहिले नै इन्स्टल गरिएको छ! पुरानो संस्करण इन्स्टल गर्न सिफारिस गरिँदैन। यदि तपाईं साँच्चै यो पुरानो संस्करण इन्स्टल गर्न चाहनुहुन्छ भने, पहिले हालको संस्करण अनइन्स्टल गर्नु राम्रो हुन्छ। तपाईंले गर्न चाहनुभएको कार्य छान्नुहोस् र जारी राख्न अर्को बटनमा क्लिक गर्नुहोस्।"
LangString older ${LANG_NEPALI} "पुरानो"
LangString olderOrUnknownVersionInstalled ${LANG_NEPALI} "तपाईंको सिस्टममा ${PRODUCTNAME} को $R4 संस्करण इन्स्टल गरिएको छ। इन्स्टल गर्नुअघि हालको संस्करण अनइन्स्टल गर्न सिफारिस गरिन्छ। तपाईंले गर्न चाहनुभएको कार्य छान्नुहोस् र जारी राख्न अर्को बटनमा क्लिक गर्नुहोस्।"
LangString silentDowngrades ${LANG_NEPALI} "यस इन्स्टलरमा पुरानो संस्करणमा फर्कन अनुमति छैन, त्यसैले साइलेन्ट इन्स्टलरबाट अगाडि बढ्न सकिँदैन। कृपया यसको सट्टा ग्राफिकल इन्टरफेस भएको इन्स्टलर प्रयोग गर्नुहोस्।$\n"
LangString unableToUninstall ${LANG_NEPALI} "अनइन्स्टल गर्न सकिएन!"
LangString uninstallApp ${LANG_NEPALI} "${PRODUCTNAME} अनइन्स्टल गर्नुहोस्"
LangString uninstallBeforeInstalling ${LANG_NEPALI} "इन्स्टल गर्नुअघि अनइन्स्टल गर्नुहोस्"
LangString unknown ${LANG_NEPALI} "अज्ञात"
LangString webview2AbortError ${LANG_NEPALI} "WebView2 इन्स्टल गर्न सकिएन! यसबिना एप चल्न सक्दैन। इन्स्टलर फेरि सुरु गरेर प्रयास गर्नुहोस्।"
LangString webview2DownloadError ${LANG_NEPALI} "त्रुटि: WebView2 डाउनलोड असफल भयो - $0"
LangString webview2DownloadSuccess ${LANG_NEPALI} "WebView2 बुटस्ट्र्यापर सफलतापूर्वक डाउनलोड भयो"
LangString webview2Downloading ${LANG_NEPALI} "WebView2 बुटस्ट्र्यापर डाउनलोड हुँदैछ..."
LangString webview2InstallError ${LANG_NEPALI} "त्रुटि: WebView2 इन्स्टल असफल भयो (exit code $1)"
LangString webview2InstallSuccess ${LANG_NEPALI} "WebView2 सफलतापूर्वक इन्स्टल भयो"
LangString deleteAppData ${LANG_NEPALI} "एप्लिकेसन डेटा मेटाउनुहोस्"
